import { Providers } from "./lib/providers";
import "./globals.css";

export const metadata = {
  title: "Believe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
